/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 27 08:43:14 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Contador_ESTest extends Contador_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Contador contador0 = new Contador(1);
      contador0.run();
      boolean boolean0 = contador0.isRunning();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Contador contador0 = new Contador(0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Contador contador0 = new Contador(1);
      contador0.run();
      int int0 = contador0.getTime();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Contador contador0 = new Contador();
      String string0 = contador0.getTimeFormatted();
      assertEquals("00:00", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Contador contador0 = new Contador();
      int int0 = contador0.getTime();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Contador contador0 = new Contador();
      boolean boolean0 = contador0.isRunning();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Contador contador0 = new Contador();
      contador0.stopCounter();
      assertFalse(contador0.isRunning());
  }
}
