/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 27 08:39:35 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Logg_ESTest extends Logg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Logg logg0 = new Logg("M+yaiqByae%|)m9IP`E");
      logg0.setDateFormat("");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Logg logg0 = new Logg((String) null);
      // Undeclared exception!
      try { 
        logg0.writeLogg((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Logg logg0 = new Logg((String) null);
      // Undeclared exception!
      try { 
        logg0.writeLogg();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Logg logg0 = new Logg((String) null);
      // Undeclared exception!
      try { 
        logg0.writeDatedLogg((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Logg logg0 = new Logg((String) null);
      // Undeclared exception!
      try { 
        logg0.writeDatedLogg();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Logg logg0 = new Logg("");
      logg0.writeDatedLogg("");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Logg logg0 = new Logg("M+yaiqByae%|)m9IP`E");
      logg0.writeDatedLogg("M+yaiqByae%|)m9IP`E");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Logg logg0 = new Logg("");
      logg0.writeLogg("_,I4~=ppSz-83FMdQ");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Logg logg0 = new Logg("M+yaiqByae%|)m9IP`E");
      logg0.writeDatedLogg();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Logg logg0 = new Logg("M+yaiqByae%|)m9IP`E");
      logg0.writeLogg("5F;:");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Logg logg0 = new Logg();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Logg logg0 = new Logg("");
      logg0.setDateFormat("MyLogg.txt");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Logg logg0 = new Logg("");
      logg0.writeLogg();
  }
}
